### ISSUE TITLE
Fails When Switching Tags

### ISSUE THREAD

**Issue by baskerville** [jimenezrick/hidcur#2]
If I spawn a terminal window on my first tag, wait for the cursor to hide, and switch to the second desktop, the mouse cursor reappears and `hidcur` ceases to work no matter what mouse activity occurs afterwards.

**Comment by jimenezrick** [comment]
Does appear any error message in `$HOME/.xsession-errors` (or any other Xorg error log) when `hidcur` dies?

**Comment by baskerville** [comment]
It doesn't die but it stays in `wait_event` forever (I've added print statements in the main loop to see what was happening).
So to sum up: I launch a terminal on my first tag, I issue `hidcur`. The cursor disappears after the default delay. Then, I switch to my second tag: the cursor reappears. Now, if I go back to the first tag, I can see that the `hidcur` process is trapped in the `wait_event` function. And it stays there no matter what X events occurs afterwards.

**Comment by jimenezrick** [comment]
I can't see what is failing, I mean, I'm no X11 expert and something for sure is happening but with my limited knowledge I can't say right know what it is :-/
